"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Convocatoria = exports.TipoEjercicio = exports.EstadoConvocatoria = void 0;
var typeorm_1 = require("typeorm");
var oposicion_entity_1 = require("../oposicion/oposicion.entity");
var documento_convocatoria_entity_1 = require("./documento-convocatoria.entity");
var tema_entity_1 = require("../tema/tema.entity");
var EstadoConvocatoria;
(function (EstadoConvocatoria) {
    EstadoConvocatoria["ACTIVA"] = "activa";
    EstadoConvocatoria["CERRADA"] = "cerrada";
    EstadoConvocatoria["BORRADOR"] = "borrador";
})(EstadoConvocatoria || (exports.EstadoConvocatoria = EstadoConvocatoria = {}));
var TipoEjercicio;
(function (TipoEjercicio) {
    TipoEjercicio["TEST"] = "test";
    TipoEjercicio["DESARROLLO"] = "desarrollo";
    TipoEjercicio["ORAL"] = "oral";
    TipoEjercicio["PRACTICO"] = "practico";
    TipoEjercicio["MIXTO"] = "mixto";
})(TipoEjercicio || (exports.TipoEjercicio = TipoEjercicio = {}));
var Convocatoria = function () {
    var _classDecorators = [(0, typeorm_1.Entity)('convocatorias')];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _anyo_decorators;
    var _anyo_initializers = [];
    var _anyo_extraInitializers = [];
    var _plazas_decorators;
    var _plazas_initializers = [];
    var _plazas_extraInitializers = [];
    var _estado_decorators;
    var _estado_initializers = [];
    var _estado_extraInitializers = [];
    var _fechaExamen_decorators;
    var _fechaExamen_initializers = [];
    var _fechaExamen_extraInitializers = [];
    var _urlInap_decorators;
    var _urlInap_initializers = [];
    var _urlInap_extraInitializers = [];
    var _diferenciasAnterior_decorators;
    var _diferenciasAnterior_initializers = [];
    var _diferenciasAnterior_extraInitializers = [];
    var _referenciaBoe_decorators;
    var _referenciaBoe_initializers = [];
    var _referenciaBoe_extraInitializers = [];
    var _plazoInscripcionInicio_decorators;
    var _plazoInscripcionInicio_initializers = [];
    var _plazoInscripcionInicio_extraInitializers = [];
    var _plazoInscripcionFin_decorators;
    var _plazoInscripcionFin_initializers = [];
    var _plazoInscripcionFin_extraInitializers = [];
    var _creadoEn_decorators;
    var _creadoEn_initializers = [];
    var _creadoEn_extraInitializers = [];
    var _numEjercicios_decorators;
    var _numEjercicios_initializers = [];
    var _numEjercicios_extraInitializers = [];
    var _tipoEjercicio_decorators;
    var _tipoEjercicio_initializers = [];
    var _tipoEjercicio_extraInitializers = [];
    var _numPreguntas_decorators;
    var _numPreguntas_initializers = [];
    var _numPreguntas_extraInitializers = [];
    var _tiempoMinutos_decorators;
    var _tiempoMinutos_initializers = [];
    var _tiempoMinutos_extraInitializers = [];
    var _permiteBlancos_decorators;
    var _permiteBlancos_initializers = [];
    var _permiteBlancos_extraInitializers = [];
    var _penalizacion_decorators;
    var _penalizacion_initializers = [];
    var _penalizacion_extraInitializers = [];
    var _fraccionPenalizacion_decorators;
    var _fraccionPenalizacion_initializers = [];
    var _fraccionPenalizacion_extraInitializers = [];
    var _notaMinimaAprobado_decorators;
    var _notaMinimaAprobado_initializers = [];
    var _notaMinimaAprobado_extraInitializers = [];
    var _oposicion_decorators;
    var _oposicion_initializers = [];
    var _oposicion_extraInitializers = [];
    var _documentos_decorators;
    var _documentos_initializers = [];
    var _documentos_extraInitializers = [];
    var _temas_decorators;
    var _temas_initializers = [];
    var _temas_extraInitializers = [];
    var Convocatoria = _classThis = /** @class */ (function () {
        function Convocatoria_1() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.anyo = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _anyo_initializers, void 0));
            this.plazas = (__runInitializers(this, _anyo_extraInitializers), __runInitializers(this, _plazas_initializers, void 0));
            this.estado = (__runInitializers(this, _plazas_extraInitializers), __runInitializers(this, _estado_initializers, void 0));
            this.fechaExamen = (__runInitializers(this, _estado_extraInitializers), __runInitializers(this, _fechaExamen_initializers, void 0));
            this.urlInap = (__runInitializers(this, _fechaExamen_extraInitializers), __runInitializers(this, _urlInap_initializers, void 0));
            this.diferenciasAnterior = (__runInitializers(this, _urlInap_extraInitializers), __runInitializers(this, _diferenciasAnterior_initializers, void 0));
            this.referenciaBoe = (__runInitializers(this, _diferenciasAnterior_extraInitializers), __runInitializers(this, _referenciaBoe_initializers, void 0));
            this.plazoInscripcionInicio = (__runInitializers(this, _referenciaBoe_extraInitializers), __runInitializers(this, _plazoInscripcionInicio_initializers, void 0));
            this.plazoInscripcionFin = (__runInitializers(this, _plazoInscripcionInicio_extraInitializers), __runInitializers(this, _plazoInscripcionFin_initializers, void 0));
            this.creadoEn = (__runInitializers(this, _plazoInscripcionFin_extraInitializers), __runInitializers(this, _creadoEn_initializers, void 0));
            this.numEjercicios = (__runInitializers(this, _creadoEn_extraInitializers), __runInitializers(this, _numEjercicios_initializers, void 0));
            this.tipoEjercicio = (__runInitializers(this, _numEjercicios_extraInitializers), __runInitializers(this, _tipoEjercicio_initializers, void 0));
            this.numPreguntas = (__runInitializers(this, _tipoEjercicio_extraInitializers), __runInitializers(this, _numPreguntas_initializers, void 0));
            this.tiempoMinutos = (__runInitializers(this, _numPreguntas_extraInitializers), __runInitializers(this, _tiempoMinutos_initializers, void 0));
            this.permiteBlancos = (__runInitializers(this, _tiempoMinutos_extraInitializers), __runInitializers(this, _permiteBlancos_initializers, void 0));
            this.penalizacion = (__runInitializers(this, _permiteBlancos_extraInitializers), __runInitializers(this, _penalizacion_initializers, void 0));
            this.fraccionPenalizacion = (__runInitializers(this, _penalizacion_extraInitializers), __runInitializers(this, _fraccionPenalizacion_initializers, void 0));
            this.notaMinimaAprobado = (__runInitializers(this, _fraccionPenalizacion_extraInitializers), __runInitializers(this, _notaMinimaAprobado_initializers, void 0));
            this.oposicion = (__runInitializers(this, _notaMinimaAprobado_extraInitializers), __runInitializers(this, _oposicion_initializers, void 0));
            this.documentos = (__runInitializers(this, _oposicion_extraInitializers), __runInitializers(this, _documentos_initializers, void 0));
            this.temas = (__runInitializers(this, _documentos_extraInitializers), __runInitializers(this, _temas_initializers, void 0));
            __runInitializers(this, _temas_extraInitializers);
        }
        return Convocatoria_1;
    }());
    __setFunctionName(_classThis, "Convocatoria");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, typeorm_1.PrimaryGeneratedColumn)('uuid')];
        _anyo_decorators = [(0, typeorm_1.Column)()];
        _plazas_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _estado_decorators = [(0, typeorm_1.Column)({ type: 'enum', enum: EstadoConvocatoria, default: EstadoConvocatoria.BORRADOR })];
        _fechaExamen_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _urlInap_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _diferenciasAnterior_decorators = [(0, typeorm_1.Column)({ type: 'text', nullable: true })];
        _referenciaBoe_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _plazoInscripcionInicio_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _plazoInscripcionFin_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _creadoEn_decorators = [(0, typeorm_1.CreateDateColumn)()];
        _numEjercicios_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _tipoEjercicio_decorators = [(0, typeorm_1.Column)({ type: 'enum', enum: TipoEjercicio, nullable: true })];
        _numPreguntas_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _tiempoMinutos_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _permiteBlancos_decorators = [(0, typeorm_1.Column)({ default: true })];
        _penalizacion_decorators = [(0, typeorm_1.Column)({ default: false })];
        _fraccionPenalizacion_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _notaMinimaAprobado_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 5, scale: 2, nullable: true })];
        _oposicion_decorators = [(0, typeorm_1.ManyToOne)(function () { return oposicion_entity_1.Oposicion; }, function (o) { return o.convocatorias; })];
        _documentos_decorators = [(0, typeorm_1.OneToMany)(function () { return documento_convocatoria_entity_1.DocumentoConvocatoria; }, function (d) { return d.convocatoria; })];
        _temas_decorators = [(0, typeorm_1.OneToMany)(function () { return tema_entity_1.Tema; }, function (t) { return t.convocatoria; })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _anyo_decorators, { kind: "field", name: "anyo", static: false, private: false, access: { has: function (obj) { return "anyo" in obj; }, get: function (obj) { return obj.anyo; }, set: function (obj, value) { obj.anyo = value; } }, metadata: _metadata }, _anyo_initializers, _anyo_extraInitializers);
        __esDecorate(null, null, _plazas_decorators, { kind: "field", name: "plazas", static: false, private: false, access: { has: function (obj) { return "plazas" in obj; }, get: function (obj) { return obj.plazas; }, set: function (obj, value) { obj.plazas = value; } }, metadata: _metadata }, _plazas_initializers, _plazas_extraInitializers);
        __esDecorate(null, null, _estado_decorators, { kind: "field", name: "estado", static: false, private: false, access: { has: function (obj) { return "estado" in obj; }, get: function (obj) { return obj.estado; }, set: function (obj, value) { obj.estado = value; } }, metadata: _metadata }, _estado_initializers, _estado_extraInitializers);
        __esDecorate(null, null, _fechaExamen_decorators, { kind: "field", name: "fechaExamen", static: false, private: false, access: { has: function (obj) { return "fechaExamen" in obj; }, get: function (obj) { return obj.fechaExamen; }, set: function (obj, value) { obj.fechaExamen = value; } }, metadata: _metadata }, _fechaExamen_initializers, _fechaExamen_extraInitializers);
        __esDecorate(null, null, _urlInap_decorators, { kind: "field", name: "urlInap", static: false, private: false, access: { has: function (obj) { return "urlInap" in obj; }, get: function (obj) { return obj.urlInap; }, set: function (obj, value) { obj.urlInap = value; } }, metadata: _metadata }, _urlInap_initializers, _urlInap_extraInitializers);
        __esDecorate(null, null, _diferenciasAnterior_decorators, { kind: "field", name: "diferenciasAnterior", static: false, private: false, access: { has: function (obj) { return "diferenciasAnterior" in obj; }, get: function (obj) { return obj.diferenciasAnterior; }, set: function (obj, value) { obj.diferenciasAnterior = value; } }, metadata: _metadata }, _diferenciasAnterior_initializers, _diferenciasAnterior_extraInitializers);
        __esDecorate(null, null, _referenciaBoe_decorators, { kind: "field", name: "referenciaBoe", static: false, private: false, access: { has: function (obj) { return "referenciaBoe" in obj; }, get: function (obj) { return obj.referenciaBoe; }, set: function (obj, value) { obj.referenciaBoe = value; } }, metadata: _metadata }, _referenciaBoe_initializers, _referenciaBoe_extraInitializers);
        __esDecorate(null, null, _plazoInscripcionInicio_decorators, { kind: "field", name: "plazoInscripcionInicio", static: false, private: false, access: { has: function (obj) { return "plazoInscripcionInicio" in obj; }, get: function (obj) { return obj.plazoInscripcionInicio; }, set: function (obj, value) { obj.plazoInscripcionInicio = value; } }, metadata: _metadata }, _plazoInscripcionInicio_initializers, _plazoInscripcionInicio_extraInitializers);
        __esDecorate(null, null, _plazoInscripcionFin_decorators, { kind: "field", name: "plazoInscripcionFin", static: false, private: false, access: { has: function (obj) { return "plazoInscripcionFin" in obj; }, get: function (obj) { return obj.plazoInscripcionFin; }, set: function (obj, value) { obj.plazoInscripcionFin = value; } }, metadata: _metadata }, _plazoInscripcionFin_initializers, _plazoInscripcionFin_extraInitializers);
        __esDecorate(null, null, _creadoEn_decorators, { kind: "field", name: "creadoEn", static: false, private: false, access: { has: function (obj) { return "creadoEn" in obj; }, get: function (obj) { return obj.creadoEn; }, set: function (obj, value) { obj.creadoEn = value; } }, metadata: _metadata }, _creadoEn_initializers, _creadoEn_extraInitializers);
        __esDecorate(null, null, _numEjercicios_decorators, { kind: "field", name: "numEjercicios", static: false, private: false, access: { has: function (obj) { return "numEjercicios" in obj; }, get: function (obj) { return obj.numEjercicios; }, set: function (obj, value) { obj.numEjercicios = value; } }, metadata: _metadata }, _numEjercicios_initializers, _numEjercicios_extraInitializers);
        __esDecorate(null, null, _tipoEjercicio_decorators, { kind: "field", name: "tipoEjercicio", static: false, private: false, access: { has: function (obj) { return "tipoEjercicio" in obj; }, get: function (obj) { return obj.tipoEjercicio; }, set: function (obj, value) { obj.tipoEjercicio = value; } }, metadata: _metadata }, _tipoEjercicio_initializers, _tipoEjercicio_extraInitializers);
        __esDecorate(null, null, _numPreguntas_decorators, { kind: "field", name: "numPreguntas", static: false, private: false, access: { has: function (obj) { return "numPreguntas" in obj; }, get: function (obj) { return obj.numPreguntas; }, set: function (obj, value) { obj.numPreguntas = value; } }, metadata: _metadata }, _numPreguntas_initializers, _numPreguntas_extraInitializers);
        __esDecorate(null, null, _tiempoMinutos_decorators, { kind: "field", name: "tiempoMinutos", static: false, private: false, access: { has: function (obj) { return "tiempoMinutos" in obj; }, get: function (obj) { return obj.tiempoMinutos; }, set: function (obj, value) { obj.tiempoMinutos = value; } }, metadata: _metadata }, _tiempoMinutos_initializers, _tiempoMinutos_extraInitializers);
        __esDecorate(null, null, _permiteBlancos_decorators, { kind: "field", name: "permiteBlancos", static: false, private: false, access: { has: function (obj) { return "permiteBlancos" in obj; }, get: function (obj) { return obj.permiteBlancos; }, set: function (obj, value) { obj.permiteBlancos = value; } }, metadata: _metadata }, _permiteBlancos_initializers, _permiteBlancos_extraInitializers);
        __esDecorate(null, null, _penalizacion_decorators, { kind: "field", name: "penalizacion", static: false, private: false, access: { has: function (obj) { return "penalizacion" in obj; }, get: function (obj) { return obj.penalizacion; }, set: function (obj, value) { obj.penalizacion = value; } }, metadata: _metadata }, _penalizacion_initializers, _penalizacion_extraInitializers);
        __esDecorate(null, null, _fraccionPenalizacion_decorators, { kind: "field", name: "fraccionPenalizacion", static: false, private: false, access: { has: function (obj) { return "fraccionPenalizacion" in obj; }, get: function (obj) { return obj.fraccionPenalizacion; }, set: function (obj, value) { obj.fraccionPenalizacion = value; } }, metadata: _metadata }, _fraccionPenalizacion_initializers, _fraccionPenalizacion_extraInitializers);
        __esDecorate(null, null, _notaMinimaAprobado_decorators, { kind: "field", name: "notaMinimaAprobado", static: false, private: false, access: { has: function (obj) { return "notaMinimaAprobado" in obj; }, get: function (obj) { return obj.notaMinimaAprobado; }, set: function (obj, value) { obj.notaMinimaAprobado = value; } }, metadata: _metadata }, _notaMinimaAprobado_initializers, _notaMinimaAprobado_extraInitializers);
        __esDecorate(null, null, _oposicion_decorators, { kind: "field", name: "oposicion", static: false, private: false, access: { has: function (obj) { return "oposicion" in obj; }, get: function (obj) { return obj.oposicion; }, set: function (obj, value) { obj.oposicion = value; } }, metadata: _metadata }, _oposicion_initializers, _oposicion_extraInitializers);
        __esDecorate(null, null, _documentos_decorators, { kind: "field", name: "documentos", static: false, private: false, access: { has: function (obj) { return "documentos" in obj; }, get: function (obj) { return obj.documentos; }, set: function (obj, value) { obj.documentos = value; } }, metadata: _metadata }, _documentos_initializers, _documentos_extraInitializers);
        __esDecorate(null, null, _temas_decorators, { kind: "field", name: "temas", static: false, private: false, access: { has: function (obj) { return "temas" in obj; }, get: function (obj) { return obj.temas; }, set: function (obj, value) { obj.temas = value; } }, metadata: _metadata }, _temas_initializers, _temas_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        Convocatoria = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return Convocatoria = _classThis;
}();
exports.Convocatoria = Convocatoria;
